POST http://localhost:3001/api/notes  HTTP/1.1
content-type: application/json

{
    "content":"Desde mongo",
    "important":true,
    "userId":"6182ad33b505251a9ec9b31e"
}
###

POST http://localhost:55200/test HTTP/1.1
content-type: application/json

{
    "cname": "weile"
}
###
POST http://localhost:55200/test HTTP/1.1
content-type: application/json
{
    "cname": "weile"
}